name: reusable/analysis
on:
  workflow_call:
    inputs:
      moduleRootDirectory:
        description: 'Defines root module directory'
        required: true
        type: string

    secrets:
      githubToken:
        description: 'GitHub Token value'
        required: true

jobs:
  checkov:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan module with checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.moduleRootDirectory }}
          quiet: false
          soft_fail: false
          compact: false
          skip_check: CKV_GIT_1 # public repo is ok
          output_file_path: ./checkov.sarif

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
        with:
          sarif_file: ./checkov.sarif

  tfsec:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

          #- name: Scan module with tfsec
          #  uses: aquasecurity/tfsec-action@v1.0.3
          #  with:
          #    working_directory: ${{ inputs.moduleRootDirectory }}
          #    github_token: ${{ secrets.githubToken }}
          #
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # v0.17.0
        with:
          scan-type: 'fs'
          scanners: misconfig,vuln,secret
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
        with:
          sarif_file: 'trivy-results.sarif'
