name: reusable/lint
on:
  workflow_call:
    secrets:
      githubToken:
        description: 'GitHub Token value'
        required: true

    inputs:
      tflintVersion:
        description: 'Defines TFLint version to use'
        required: true
        type: string

      moduleRootDirectory:
        description: 'Defines root module directory'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4.0.0
        with:
          tflint_version: ${{ inputs.tflintVersion }}
          github_token: ${{ secrets.githubToken }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
        run: |
          tflint -c ${{ github.workspace }}/.tflint.hcl --init && \
          tflint -c ${{ github.workspace }}/.tflint.hcl


          #      - name: Setup TFLint
          #        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4.0.0
          #        with:
          #          tflint_version: v0.48.0
          #
          #      - name: Terraform lint
          #        run: |
          #          echo "pwd: $(pwd)"
          #          tflint -f compact
