name: reusable-auto-approve
on:
  workflow_call:
jobs:
  auto-approve-plan:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      #  - name: Generate token  # Why ?
      #  id: generate_token
      #  uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a  # v.2.1.0
      #  with:
      #    app_id: ${{ secrets.GH_APP_ID }}
      #    private_key: ${{ secrets.GH_APP_PEM_FILE }}
      #- name: authenticate to git with app token  # Why ?
      #  run: |
      #    echo ${{ steps.generate_token.outputs.token }} | gh auth login --with-token
      #    gh auth setup-git
      - name: approve workflow run only if
        run: |-
          ENV_ID=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --jq '.[].environment.id')
          echo "ENV_ID: ${ENV_ID}"
          ENV_NAME=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --jq '.[].environment.name')
          echo "ENV_NAME: ${ENV_NAME}"
          JOB_NAME=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[] | select(.status == "waiting").name')
          echo "JOB_NAME: ${JOB_NAME}"
          if [[ "$JOB_NAME" == *"plan / plan" ]] ; then
            echo "auto approving this job, since its a plan (I hope!) "
            RESULT=$(gh api --verbose repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --method POST -F "environment_ids[]=${ENV_ID}" -f "state=approved" -f "comment=Autoapproved since its a plan")
            echo "done, this is how it went: $RESULT"
          else
            echo "auto approve will not run, since job name does not end with 'plan / plan'"
          fi
