name: reusable-auto-approve
on:
  workflow_call:
    inputs:
      environment:
        description: Environment to run tests against
        type: string
        required: true
jobs:
  auto-approve:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate token # Why ?
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v.2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PEM_FILE }}
      - name: authenticate to git with app token # Why ?
        run: |
          echo ${{ steps.generate_token.outputs.token }} | gh auth login --with-token
          gh auth setup-git
      - name: approve workflow run
        run: |-
          gh api --verbose repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments
