name: GitHub Release

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

    secrets:
      githubToken:
        description: 'GitHub Token value'
        required: true
      


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
        with:
          node-version: 20.x # optional

      - name: Install Semantic Release and plugins
        run: |
          npm install semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/github

      - name: Create Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.githubToken }}





