name: terraform plan (aws-root-account)

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/aws-root-account-plan.yml'
      - '.github/workflows/aws-root-account-apply.yml'
  workflow_dispatch:

jobs:
  plan:
    environment: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
        #defaults:
      #run:
      #  working-directory: ./terraform
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          #role-to-assume: arn:aws:iam::${{secrets.AWS_ROOT_ACCOUNT_ID}}:role/github-actions-plan
          role-to-assume: arn:aws:iam::${{secrets.AWS_ROOT_ACCOUNT}}:role/AWS-GitHubActions-OIDC_role

          role-session-name: GitHubActions
          aws-region: eu-north-1
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: 1.5.2
      - run: terraform fmt -check
        continue-on-error: true
      - run: terraform init
      - run: terraform validate -no-color
      - run: terraform plan -no-color
   
